version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-hw-12
    ports:
      - "6379:6379"

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db:5432/contacts_db
      - SECRET_KEY=your-very-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
      - REDIS_HOST=redis # Connect to the redis container by its service name
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
